Leykoz/Areas/AdminPanel/Controllers/SaviorController.cs
using System;
using System.Diagnostics;
using System.IO;
using System.Threading.Tasks;
using ClosedXML.Excel;
using Leykoz.Business.Service.Interfaces;
using Leykoz.Business.ViewModels;
using Leykoz.Core.Entities;
using Leykoz.Data.DAL;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Leykoz.Areas.AdminPanel.Controllers
{
    [Area("AdminPanel")]
    [Authorize]
    public class SaviorController : Controller
    {
        private readonly IUnitOfWorkService _unitOfWorkService;
        // private readonly AppDbContext _context;

        public SaviorController(IUnitOfWorkService unitOfWorkService)
        {
            _unitOfWorkService = unitOfWorkService;
            // _context = context;
        }

        public async Task<IActionResult> Index(int page = 1)
        {
            // await CreateSaviorData(5000);
            // await CreateSaviorDataFast(150);
            // Stopwatch t = new Stopwatch();
            // t.Start();
            // await CreateNews(3500);
            Paginate<Savior> DbData = await _unitOfWorkService.SaviorService.GetAllAsync(page, 10);

            // t.Stop();
            // Console.WriteLine(t.ElapsedMilliseconds );
            return View(DbData);
        }


        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                await _unitOfWorkService.SaviorService.DeleteAsync(id);
            }
            catch
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Search(string search, int page = 0)
        {
            if (search is null)
            {
                return View();
            }

            PaginateFast<Savior> saviors = null;
            if (page != 0)
            {
                saviors = await _unitOfWorkService.SaviorService.GetAllPaginatedSAsync(
                    search,
                    page, 10);
                saviors.search = search;
            }

            return View(saviors);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Search(PaginateFast<Savior> paginateFast)
        {
            if (paginateFast.search is null)
            {
                return View();
            }

            Stopwatch t = new Stopwatch();
            t.Start();
            paginateFast.CurrentPage = paginateFast.CurrentPage == 0 ? 1 : paginateFast.CurrentPage;
            PaginateFast<Savior> saviors = await _unitOfWorkService.SaviorService.GetAllPaginatedSAsync(
                paginateFast.search,
                paginateFast.CurrentPage, 10);
            saviors.search = paginateFast.search;

            t.Stop();
            Console.WriteLine("axtaris muddeti   " + t.ElapsedMilliseconds);
            return View(saviors);
        }

        
    }
}

Leykoz/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using ClosedXML.Excel;
using Leykoz.Business.Service.Interfaces;
using Leykoz.Business.ViewModels;
using Leykoz.Core.Entities;
using Leykoz.Data.DAL;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Leykoz.Controllers
{
    public class ReportController : Controller
    {
        private readonly IUnitOfWorkService _unitOfWorkService;
        private readonly AppDbContext _context;

        public ReportController(IUnitOfWorkService unitOfWorkService, AppDbContext context)
        {
            _context = context;
            _unitOfWorkService = unitOfWorkService;
        }


        // GET
        public async Task<IActionResult> Index(int page = 1)
        {
            ViewBag.Setting = await _unitOfWorkService.SiteSettingService.GetAllAsync();
            var c = await _unitOfWorkService.ReportAmountService.GetPasinateAllAsync(page, 9);
            return View(await _unitOfWorkService.ReportAmountService.GetPasinateAllAsync(page, 9));
        }

        public async Task<IActionResult> ExportToExcel(int id)
        {
            ReportYearVM reportYearVm = await _unitOfWorkService.ReportYearService.GetByIdAsync(id);
            if (reportYearVm is null)
            {
                return RedirectToAction("Index", "Home");
            }

            using (var workbook = new XLWorkbook())
            {
                var worksheet = workbook.Worksheets.Add("Reports");
                var currentRow = 1;
                worksheet.Cell(currentRow, 1).Value = "Ad";
                worksheet.Cell(currentRow, 2).Value = "Soyad";
                worksheet.Cell(currentRow, 3).Value = "Məxfi Ad";
                worksheet.Cell(currentRow, 4).Value = "Məbləğ";
                worksheet.Cell(currentRow, 5).Value = "Tarix";

                worksheet.Cell(currentRow, 1).Style.Fill.SetBackgroundColor(XLColor.LightGray);
                worksheet.Cell(currentRow, 2).Style.Fill.SetBackgroundColor(XLColor.LightGray);
                worksheet.Cell(currentRow, 3).Style.Fill.SetBackgroundColor(XLColor.LightGray);
                worksheet.Cell(currentRow, 4).Style.Fill.SetBackgroundColor(XLColor.LightGray);
                worksheet.Cell(currentRow, 5).Style.Fill.SetBackgroundColor(XLColor.LightGray);

                // List<ReportAmount> amounts = await _unitOfWorkService.ReportAmountService.GetAllByDateAsync(reportYearVm.Year);
                List<ReportAmount> amounts =
                  await  _context
                        .ReportAmounts
                        .Where(p => p.IsDeleted == false && p.CreatedAt.Year ==reportYearVm.Year.Year )
                        .Include(p=>p.Report)
                        .Where(p=>p.Report.IsDeleted==false)
                        .ToListAsync();

                foreach (var Report in amounts)
                {
                    currentRow++;
                    worksheet.Cell(currentRow, 1).Value = Report.Report.Name;
                    worksheet.Cell(currentRow, 2).Value = Report.Report.SurName;
                    worksheet.Cell(currentRow, 3).Value = Report.Report.PrivateName;
                    worksheet.Cell(currentRow, 4).Value = Report.Amount;
                    worksheet.Cell(currentRow, 5).Value = Report.CreatedAt;
                }

                using (var stream = new MemoryStream())
                {
                    workbook.SaveAs(stream);
                    var content = stream.ToArray();
                    return File(content, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                        $"Reports_{DateTime.Now.ToString()}.xlsx");
                }
            }
        }
    }
}

Leykoz/Areas/AdminPanel/Views/Savior/Index.cshtml
@model Paginate<Savior>
@{
    int count = ((Model.CurrentPage - 1) * 10) + 1;
}
<!-- ============================================================== -->
<!-- Start Page Content here -->
<!-- ============================================================== -->

<div class="content-page">
    <div class="content">

        <!-- Start Content-->
        <div class="container-fluid">

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body table-responsive">
                            <h4 class="m-t-0 header-title mb-4">
                                <b>Xilaskarlar</b>
                            </h4>
                            <div class="col-sm-12 col-md-6">
                                <a asp-controller="Savior" asp-action="Search">
                                    <button type="button" class="btn btn-primary btn-rounded waves-effect width-md waves-light my-2">Search</button>
                                </a>

                            </div>
                            <table id="datatable-buttons" class="table table-striped table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">

                                <thead>
                                <tr>
                                    <th>№</th>
                                    <th>Adı, Soyadı</th>
                                    <th>Email</th>
                                    <th>Əlaqə Nömrəsi</th>
                                    <th>Müraciyyətin tipi</th>
                                    <th>Müraciyyətin</th>
                                    <th>Tarix</th>
                                    <th>Parametrlər</th>
                                </tr>
                                </thead>

                                <tbody>
                                @foreach (var savior in Model.Items)
                                {
                                    <tr>
                                        <td>@count</td>
                                        <td>@savior.FullName.ToUpper()</td>
                                        <td>@savior.Email.ToUpper()</td>
                                        <td>@savior.Phone</td>
                                        <td>@savior.ApplyType</td>
                                        <td>@savior.ApplyContent</td>
                                        <td>@savior.CreatedDate</td>
                                        <td>

                                            @* <a class="btn btn-icon waves-effect waves-light btn-primary" asp-controller="Report" asp-action="Create" asp-route-id="@savior.Id"> *@
                                            @*     <i class="  ion ion-ios-add-circle-outline"></i> *@
                                            @* </a> *@
                                            <a class="btn btn-icon waves-effect waves-light btn-danger my-2" asp-action="Delete" asp-route-id="@savior.Id">
                                                <i class="mdi mdi-delete-outline"></i>
                                            </a>
                                        </td>

                                    </tr>

                                    count++;
                                }
                                </tbody>
                            </table>
                        </div>
                        @if (@Model.AllPageCount > 1)
                        {
                            <div class="col-12 d-flex justify-content-center my-3">
                                <nav aria-label="Page navigation example">
                                    <ul class="pagination justify-content-end">
                                        @{
                                            if (Model.CurrentPage < 1)
                                            {
                                                Model.CurrentPage = 1;
                                            }

                                            int PageLeft = 3;
                                            int PagesRight = 3;

                                            var fromPage = Math.Max(1, Model.CurrentPage - PageLeft);
                                            var toPage = Math.Min(Model.AllPageCount, Model.CurrentPage + PagesRight);

                                            if (Model.AllPageCount == toPage)
                                            {
                                                toPage = Model.AllPageCount;
                                            }

                                            if (Model.CurrentPage > 1)
                                            {
                                                <li class="page-item">
                                                    <a class="page-link" asp-route-page="@(Model.CurrentPage - 1)">
                                                        <i class="fas fa-caret-left"></i>
                                                    </a>
                                                </li>
                                                if (Model.CurrentPage - 1 > 1)
                                                {
                                                    <li class="page-item">
                                                        <a class="page-link" asp-route-page="1">1</a>
                                                    </li>
                                                }
                                            }

                                            if (fromPage - 1 > 1)
                                            {
                                                <li>
                                                    <a class="page-link" asp-route-page="@Model.CurrentPage">...</a>
                                                </li>
                                            }

                                            for (var i = fromPage; i <= toPage; i++)
                                            {
                                                <li class="page-item @(Model.CurrentPage == i ? "active" : "")">
                                                    <a class="page-link" asp-route-page="@i">@i</a>
                                                </li>
                                            }
                                            if (toPage < Model.AllPageCount - 1)
                                            {
                                                <li>
                                                    <a class="page-link" asp-route-page="@Model.CurrentPage">...</a>
                                                </li>
                                            }
                                            if (Model.AllPageCount > Model.CurrentPage)
                                            {
                                                if (Model.AllPageCount > Model.CurrentPage + 1)
                                                {
                                                    <li class="page-item">
                                                        <a class="page-link" asp-route-page="@(Model.AllPageCount)">@Model.AllPageCount</a>
                                                    </li>
                                                }
                                                <li class="page-item">
                                                    <a class="page-link" asp-route-page="@(Model.CurrentPage + 1)">
                                                        <i class="fas fa-caret-right"></i>
                                                    </a>
                                                </li>
                                            }
                                        }
                                    </ul>
                                </nav>
                            </div>
                        }

                    </div>
                </div>
            </div>

        </div>
        <!-- end container-fluid -->

    </div>
    <!-- end content -->

</div>

<!-- ============================================================== -->
<!-- End Page content -->
<!-- ============================================================== -->

Leykoz/Areas/AdminPanel/Views/Savior/Search.cshtml
@model PaginateFast<Savior>
@{
    int count = Model != null ? ((Model.CurrentPage - 1) * 10) + 1 : 0;
}
<!-- ============================================================== -->
<!-- Start Page Content here -->
<!-- ============================================================== -->

<div class="content-page">
    <div class="content">
        <!-- Start Content-->
        <div class="container-fluid">

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body table-responsive">
                            <h4 class="m-t-0 header-title mb-4">
                                <b>Xilaskarlar</b>
                            </h4>
                            <div class="col-sm-12 col-md-6">
                                <form method="post">
                                    <div id="datatable-buttons_filter" class="dataTables_filter">
                                        <label>
                                            Axtarış:
                                            <input asp-for="search" type="search" required class="form-control form-control-sm" placeholder="" aria-controls="datatable-buttons">
                                        </label>

                                        <button class="btn-primary" type="submit">search</button>
                                    </div>
                                </form>
                            </div>

                            @if (Model != null)
                            {
                                <table id="datatable-buttons" class="table table-striped table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">

                                    <thead>
                                    <tr>
                                        <th>№</th>
                                        <th>Adı, Soyadı</th>
                                        <th>Email</th>
                                        <th>Əlaqə Nömrəsi</th>
                                        <th>Müraciyyətin tipi</th>
                                        <th>Müraciyyətin</th>
                                        <th>Tarix</th>
                                        <th>Parametrlər</th>
                                    </tr>
                                    </thead>

                                    <tbody>
                                    @foreach (var savior in Model.Items)
                                    {
                                        <tr>
                                            <td>@count</td>
                                            <td>@savior.FullName.ToUpper()</td>
                                            <td>@savior.Email.ToUpper()</td>
                                            <td>@savior.Phone</td>
                                            <td>@savior.ApplyType</td>
                                            <td>@savior.ApplyContent</td>
                                            <td>@savior.CreatedDate</td>
                                            <td>
                                                @* <a class="btn btn-icon waves-effect waves-light btn-primary" asp-controller="Report" asp-action="Create" asp-route-id="@savior.Id"> *@
                                                @*     <i class="  ion ion-ios-add-circle-outline"></i> *@
                                                @* </a> *@
                                                <a class="btn btn-icon waves-effect waves-light btn-danger" asp-action="Delete" asp-route-id="@savior.Id">
                                                    <i class="mdi mdi-delete-outline"></i>
                                                </a>
                                            </td>

                                        </tr>

                                        count++;
                                    }

                                    </tbody>
                                </table>
                            }
                        </div>
                        @if (Model != null)
                        {
                            @if (@Model.AllPageCount > 1)
                            {
                                <div class="col-12 d-flex justify-content-center my-3">
                                    <nav aria-label="Page navigation example">
                                        <ul class="pagination justify-content-end">
                                            @{
                                                if (Model.CurrentPage < 1)
                                                {
                                                    Model.CurrentPage = 1;
                                                }

                                                int PageLeft = 3;
                                                int PagesRight = 3;

                                                var fromPage = Math.Max(1, Model.CurrentPage - PageLeft);
                                                var toPage = Math.Min(Model.AllPageCount, Model.CurrentPage + PagesRight);

                                                if (Model.AllPageCount == toPage)
                                                {
                                                    toPage = Model.AllPageCount;
                                                }

                                                if (Model.CurrentPage > 1)
                                                {
                                                    <li class="page-item">
                                                        <a class="page-link" asp-route-search="@Model.search" asp-route-page="@(Model.CurrentPage - 1)">
                                                            <i class="fas fa-caret-left"></i>
                                                        </a>
                                                    </li>
                                                    if (Model.CurrentPage - 1 > 1)
                                                    {
                                                        <li class="page-item">
                                                            <a class="page-link" asp-route-search="@Model.search" asp-route-page="1">1</a>
                                                        </li>
                                                    }
                                                }

                                                if (fromPage - 1 > 1)
                                                {
                                                    <li>
                                                        <a class="page-link" asp-route-search="@Model.search" asp-route-page="@Model.CurrentPage">...</a>
                                                    </li>
                                                }

                                                for (var i = fromPage; i <= toPage; i++)
                                                {
                                                    <li class="page-item @(Model.CurrentPage == i ? "active" : "")">
                                                        <a class="page-link" asp-route-search="@Model.search" asp-route-page="@i">@i</a>
                                                    </li>
                                                }
                                                if (toPage < Model.AllPageCount - 1)
                                                {
                                                    <li>
                                                        <a class="page-link" asp-route-search="@Model.search" asp-route-page="@Model.CurrentPage">...</a>
                                                    </li>
                                                }
                                                if (Model.AllPageCount > Model.CurrentPage)
                                                {
                                                    if (Model.AllPageCount > Model.CurrentPage + 1)
                                                    {
                                                        <li class="page-item">
                                                            <a class="page-link" asp-route-search="@Model.search" asp-route-page="@(Model.AllPageCount)">@Model.AllPageCount</a>
                                                        </li>
                                                    }
                                                    <li class="page-item">
                                                        <a class="page-link" asp-route-search="@Model.search" asp-route-page="@(Model.CurrentPage + 1)">
                                                            <i class="fas fa-caret-right"></i>
                                                        </a>
                                                    </li>
                                                }
                                            }
                                        </ul>
                                    </nav>
                                </div>
                            }
                        }
                    </div>
                </div>
            </div>

        </div>
        <!-- end container-fluid -->

    </div>
    <!-- end content -->

</div>